{
 "title": "Dashboard HA",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Gas verbruik",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "m3", "label": "m3" }
   ],
   "targets": [
    {
     "alias": "m3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "m3/h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hourly_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Elektriciteit verbruik",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "kWh" }
   ],
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Huidig verbruik",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Opbrengst",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "pv_power" }
     ]
    }
   ]
  },
  {
   "title": "Huidig verbruik",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "format": "m3",
   "valueName": "current",
   "targets": [
    {
     "measurement": "m3/h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hourly_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Stroom verbruik",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Zonnepanelen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "kW" }
   ],
   "targets": [
    {
     "alias": "kW",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_production" }
     ]
    }
   ]
  },
  {
   "title": "Gas verbruik",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "format": "m3",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "m3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Stroom kosten per dag",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Verbruik",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_power_consumption" }
     ]
    },
    {
     "alias": "Kosten",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "euro",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_power_price" }
     ]
    }
   ]
  },
  {
   "title": "Gas kosten per dag",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "Verbruik",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "m3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_gas_consumption" }
     ]
    },
    {
     "alias": "Kosten",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "euro",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "todays_gas_price" }
     ]
    }
   ]
  }
 ]
}